version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  restful-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restful-service-container
    ports:
      - "4000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db

volumes:
  database-volume:

networks:
  backend-network:
    driver: bridge
